fix: errors resolved while creating distribution
tefi-app/tefi-electron-app pull request #6
Opened 2023-02-28 10:25 UTC by abrehmaaan

2023-02-28 11:00 UTC, Fahad-Mahmood approved these changes

2023-02-28 12:16 UTC, Fahad-Mahmood requested changes
Aogra screen isn't working. Please look into that.

2023-03-02 08:49 UTC, abrehmaaan commented
@Fahad-Mahmood Please check now!

2023-03-02 15:34 UTC, Fahad-Mahmood approved these changes
Good, please update the release file.

2023-03-02 15:55 UTC, merged